Set outdir in tsconfig.json
Due to the way that typescript works in nodejs module resolution, the
index.d.ts file will load .ts files incorrectly if you publish the .js
and .d.ts files in alongside the .ts files.

Unfortunately this causes my version of typescript to attempt to compile
the module's .ts files which are not working with typescript 4.4.3!

See https://github.com/microsoft/TypeScript/issues/10704 which considers
this to be 'working as intended'

The solution is to avoid outputting your .js and .d.ts files into the
same location as the .ts files.

Unfortunately, adding 'dist/index.d.ts' to the types in the package.json
caused all imports of '..' (pointing to the /index.ts file) to trigger
this issue:
https://github.com/Microsoft/TypeScript/issues/14538#issuecomment-917364175
which I solved by changing those to '../index' or '../../index' etc.

Here is the error I get while trying to compile my project which uses
"typescript": "^4.4.3" after `npm install typed-cli:

```
node_modules/typed-cli/src/pipeline.ts:23:9 - error TS2322: Type
'unknown' is not assignable to type 'Error | undefined'.
  Type 'unknown' is not assignable to type 'Error'.

23         return e;
           ~~~~~~~~~

Found 1 error.
```